In [1]:
# Daniel Wingo

# Load libraries
import pandas as pd
from pandas.plotting import scatter_matrix
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

class SklearnHelper(object):
    def __init__(self, clf, seed=0, params=None):
        params['random_state'] = seed
        self.clf = clf(**params)

    def train(self, x_train, y_train):
        self.clf.fit(x_train, y_train)

    def predict(self, x):
        return self.clf.predict(x)
    
    def fit(self,x,y):
        return self.clf.fit(x,y)
    
    def feature_importances(self,x,y):
        print(self.clf.fit(x,y).feature_importances_)

In [4]:
# read in the CSV's
EMT = pd.read_csv(r'/media/sf_OS_Share/dataScience/callsforservicefiltered2018.csv')

In [5]:
# find null values "missing values"
EMT.isnull().sum()

calltime           0
callsource         0
city             180
nature             2
nature2       108188
priority          42
rptonly            0
service            2
agency             0
district       11110
statbeat       11109
ra             11113
gp             11520
primeunit      12355
cancelled          0
closecode          0
timeclose          0
calldow            0
secs2rt            0
secs2di            0
secs2en            0
secs2ar            0
secs2tr            0
secs2lc            0
secsdi2en          0
secsdi2ar          0
secsar2tr          0
secsar2lc          0
secsrt2dsp         0
secstr2lc          0
firstdisp      13091
dtype: int64

In [7]:
#check dimensions of the file
print(EMT.shape)

(124252, 31)

In [8]:
EMT.describe()

,calldow,secs2rt,secs2di,secs2en,secs2ar,secs2tr,secs2lc,secsdi2en,secsdi2ar,secsar2tr,secsar2lc,secsrt2dsp,secstr2lc
count,124252.000000,124252.000000,1.242520e+05,1.242520e+05,1.242520e+05,124252.000000,1.242520e+05,124252.000000,124252.000000,124252.000000,1.242520e+05,1.242520e+05,1.242520e+05
mean,4.076313,41.152666,3.805311e+03,3.827892e+03,4.005648e+03,626.579637,6.238722e+03,24.423518,390.542156,491.985344,2.025514e+03,3.764431e+03,7.241183e+02
std,1.926030,142.379225,6.401513e+04,6.401385e+04,6.207472e+04,1596.717496,6.425184e+04,82.111119,994.951612,970.639852,6.956322e+03,6.400863e+04,4.027293e+03
min,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,6.050000e+02,0.000000,0.000000,0.000000,2.780000e+02,0.000000e+00,0.000000e+00
50%,4.000000,13.000000,3.800000e+01,7.300000e+01,3.760000e+02,0.000000,1.856000e+03,13.000000,302.000000,0.000000,1.086000e+03,1.500000e+01,0.000000e+00
75%,6.000000,47.000000,9.400000e+01,1.310000e+02,6.820000e+02,1091.000000,3.807000e+03,31.000000,560.000000,925.000000,2.988000e+03,4.200000e+01,1.459000e+03
max,7.000000,12710.000000,2.851675e+06,2.851675e+06,2.838796e+06,95418.000000,2.851815e+06,6818.000000,159774.000000,71822.000000,1.310609e+06,2.849956e+06,1.309689e+06

In [14]:
# starting to look into the data and see what we have
#look at the All sources 
print(EMT.groupby('callsource').size())

callsource
ALARM     1343
E911     42742
M11          1
M20          1
M261         1
MA32         1
PHONE    25315
RADIO      135
RPTO        67
SELF     32444
STATE       17
TEXT         4
W911     18942
XFER      3239
dtype: int64

In [15]:
# looking at the nature of the calls
print(EMT.groupby('nature').size())

nature
911 UNKNOWN                        886
ABDOMINAL PAIN / PROBLEMS         1065
ACCIDENT HIT & RUN W/PI-REPORT       1
ACCIDENT HIT AND RUN PERS INJ       26
ACCIDENT HIT AND RUN PROP DAM      152
ACCIDENT MCI LEVEL 1                 2
ACCIDENT PI W/ WATER                 1
ACCIDENT PI W/TRACTOR TRAILER        3
ACCIDENT W/ INJURY PIN IN           88
ACCIDENT W/INJURY-GPD REPORT         5
ACCIDENT WITH FIRE                   2
ACCIDENT WITH PERSONAL INJURY     4275
ACCIDENT WITH PROPERTY DAMAGE     1383
AIR ALERT 1 LARGE AIRCRAFT           5
AIR ALERT 1 SMALL AIRCRAFT           7
AIR ALERT 2 LARGE AIRCRAFT           4
AIR ALERT 2 SMALL AIRCRAFT           3
AIR ALERT 3 SMALL AIRCRAFT           2
AIRCRAFT EMERGENCY                   2
ALARMS                             618
ALLERGIES-HIVES-STINGS             479
ANIMAL BITES / ATTACKS              75
ANIMAL RELATED CALL                509
ARMED SUBJECT                       59
ARSON INVESTIGATION                  1
ASSAULT (NO EMS NEEDED)            308
ASSAULT / RAPE                     568
ATV                                  4
AUTO THEFT                          97
BACK PAIN (NON-TRAUMATIC)          495
                                  ...
ZCONFINED                          715
ZCRUELTY                            24
ZCRUELTY FOLLOW UP                  11
ZDANGEROUS / VICIOUS CALL           25
ZDOG LOCKED IN VEHICLE              83
ZEXPOSURE                           49
ZFOLLOW UP                         852
ZHOME RABIES SHOTS                  97
ZINJURED ANIMAL                    499
ZMISTREATMENT                        7
ZMISTREATMENT FOLLOW UP              2
ZOTHER ANIMAL IN RESIDENCE         125
ZOWNER TRAP                        238
ZPICK UP TRAP                       33
ZPUBLIC NUISANCE                   225
ZPUBLIC NUISANCE FOLLOW UP          35
ZRETURN TO OWNER                    72
ZRUNNING AT LARGE                 1392
ZSERVING PAPERS                     19
ZSET A TRAP                         75
ZSICK ANIMAL                       181
ZSURRENDER ANIMAL                  149
ZTETHERING CALL                    156
ZTETHERING FOLLOW UP                93
ZTRANSPORT FROM VET                  5
ZTRANSPORT TO VET                   65
ZTRAP                               83
ZVICIOUS ANIMAL                    257
ZVICIOUS DOG INVESTIGATION           4
ZWELFARE CHECK FOLLOW UP           628
Length: 239, dtype: int64

In [16]:
#Looking at which Services the people requested
print(EMT.groupby('service').size())

service
EMS     51142
FIRE     9484
LAW     53121
OTHR    10503
dtype: int64

In [18]:
# looing at the disricts in which the call was made
print(EMT.groupby('district').size())

district
ALAM      624
ALCO      174
APD        87
APPD      148
B1       8381
B2       9953
B3A      7052
B3B      2290
B4A      3295
B4B      5984
B5       2100
B59      2340
B6       9339
BFD         6
BPD       100
CLFX      240
CLMX      113
DRFD        3
ELON        3
FD13      658
FD14       10
FD28       78
FORS       25
GBVL      595
GFD1      202
GFD2       75
GFD3      359
GFD4       33
GFD5       27
GIPD       63
GLRD      223
GPD1     4556
GPD2     3421
GPD3     2394
GPD4     2060
HPFD       63
HPPD     2975
HTFD        7
JULN       69
KFD        13
KMVL       48
KPD        12
MCVL      686
MTHP      256
NEFD      513
OKRD      440
PCSF     1579
PLGD      557
PTIA       41
RAND       77
ROCK       42
SD1      9856
SD2     13862
SD3     13433
SEFD      117
SMFD      697
STKD      419
WHTS      369
dtype: int64

In [19]:
# looking what calls were cancelled 
print(EMT.groupby('cancelled').size())

cancelled
False    111272
True      12980
dtype: int64